default['python_server']['user'] = 'vagrant'
default['python_server']['group'] = 'vagrant'
default['python_server']['name'] = 'vagrant'
default['python_server']['config'] = 'python_server.conf'
default['python_server']['document_root'] = '/the_app'
default['dal']['app_path'] = '/the_app/dal'
default['dal']['repository'] = 'https://github.com/communitydj/communitydj-dal.git'
default['frontend']['app_path'] = '/the_app/static'
default['frontend']['repository'] = 'https://github.com/communitydj/communitydj-frontend.git'

default['python']['version'] = '3.3'